[Interface]
PrivateKey = 4DADi9r94m80+Qn3Ceno1zciURqptVwetaJnvyPGM1I=
Address = 10.10.1.1/24
ListenPort = 51828
PostUp = /config/postup.sh
PostDown = /config/postdown.sh

[Peer]
PublicKey = +vEmKXtwPDhlg5kB7cXWf4EWGKXfgGgJLSKHBglbNHU=
AllowedIPs = 10.10.1.2/32
PersistentKeepalive = 25
